In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# Este lo uso por comodidad y para hacer pruebas pero lo mismo lo vamos dejando en TIF.py
class Info:
    """ Clase para almacenar información acerca del registro de datos"""

    def __init__(self, experimenter:str, subject_info:dict, ch_names:list | str, ch_types:list | str, bads:list | str, description:str, fm:float = 512):
        """
            Genera un objeto Info()
            Args:
                experimenter : Nombre del experimentador.
                subject_info : Información adicional del sujeto.
                ch_names : Lista con los nombres de los canales.
                ch_types : Tipo de cada canal ('emg', 'eeg', 'ecg') o un único tipo para todos.
                bads : Lista de canales marcados como "malos ".
                fm : Frecuencia de muestreo en Hz (por defecto 512).
                description : Descripción del registro de datos."""
        
        if len(ch_names) != len(ch_types):
            raise ValueError ("La cantidad de canales y los tipos de canales deben tener la misma longuitud")
        
        self.data = {"Experimentador": experimenter,
                     "Sujeto":subject_info,
                     "Nombre canales": ch_names,
                     "Tipo canales": ch_types,
                     "Canales malos": bads,
                     "Descripción": description,
                     "Frecuencia muestreo": fm}        

    def __contains__(self, clave):
        """ Permite verificar si una clave esta presente en el objeto
            Args:
                clave : Nombre de la clave que se quiere verificar
            Returns:
                True: La clave se encuentra en el objeto
                False: La clave no se encuentra en el objeto"""
        
        if clave in self.data:
            return True
        else:
            return False
        
    def __getitem__(self, clave):
        """ Permite acceder a elementos como un diccionario
            Args
                clave: Nombre de la clave a la que se quiere acceder
            Returns
                Devuelve el valor asociado a la clave ingrsada, o
                False: Cuando la clave ingresada no existe """
        
        if self.__contains__(clave) == True:
            return self.data[clave]
        else:
            return False
        
    def __len__(self) -> int:
        """ Devuelve la cantidad de elementos almacenados"""
        return len(self.data)
    
    def keys(self):
        """ Devuelve las claves del objeto"""
        return [clave for clave in self.data]
    
    def get(self, clave):
        """ Obtiene solo el valor de una clave específica
            Args:
                clave : Clave de la cual se quiere conocer su valor
            Returns:
                Devuleve el valor de la clave si la misma existe, o false en caso de que no exista"""
        
        if self.__contains__(clave) == True:
            return self.data[clave]
        else:
            return False

    def item(self, elemento):
        """ Devuelve los elementos como pares clave-valor de una clave en específica
            Args
                elemento : Elemento del que se quiere obtener la clave y su valor
            Returns:
                tuple : Tupla que contiene la clave y el valor del elemento
                False : Si no exite la clave en el diccionario"""
        
        valor = self.__getitem__(elemento)
        if valor == False:
            return False
        else:
            return (elemento, valor)
        
    def _check_channel(self, channel_name):
        """ Verifica si un canal se encuentra entre los nombres de los canales
            Args:
                channel_name : Canal a verificar si se encuentra en la lista de canales"""
        
        if channel_name in self.data["Nombre canales"]:
            return True
        else:
            return False
        
    def rename_channels(self, nombre_canal, nuevo_nombre):
        """Permite renombrar canales de forma segura
            Args:
                nombre_canal : Nombre del canal que se quiere cambiar
                nuevo_nombre : Nuevo nombre que va a tener el canal
            Returs:
                True : Si se cambio el nombre del canal correctamente
                False: Si no se pudo modificar el nombre del canal"""
        
        if self._check_channel(nombre_canal) == True:
            indice = self.data["Nombre canales"].index(nombre_canal)
            self.data["Nombre canales"][indice] = nuevo_nombre
            return True
        else:
            return False

In [3]:
canales = [i +1 for i in range(3)]
tipos_canales = ["ecg"] * len(canales)
sujeto = {"Nombre": "Juan Acosta",
          "Edad": 26}

In [4]:
info = Info("Juan Acosta", sujeto, canales, tipos_canales, None, "Pruebita", 512)
# print(info.__contains__("Experimentador"))

print("Nombre del experimentador:", info.__getitem__("Experimentador"))

print(info.__len__())  # Cantidad de elementos almacenados
print(info.keys()) 

print(info.item("Experimentador"))

Nombre del experimentador: Juan Acosta
7
['Experimentador', 'Sujeto', 'Nombre canales', 'Tipo canales', 'Canales malos', 'Descripción', 'Frecuencia muestreo']
('Experimentador', 'Juan Acosta')

In [5]:
# Cambio el nombre de un canal
info.rename_channels(2, 5)
print(info.item("Nombre canales"))

('Nombre canales', [1, 5, 3])

In [ ]:
class Anotaciones:
    """ Almacena y gestiona información relacionada con eventos en registros fisiológicos. 
        Permite la adición, eliminación y modificación de eventos."""
    
    def __init__(self, onset:np.ndarray, duration:np.ndarray, description):
        """Inicializa la clase con los datos de las anotaciones"""
        self.onset = onset
        self.duration = duration
        self.description = description

        if len(onset) != len(duration):
            raise ValueError ("Onset y duration deben tener la misma cantidad de elementos")
        
        self.anotaciones = pd.DataFrame({"Inicio (s)": self.onset, "Duración (s)": self.duration, "Descripcion": self.description})

    def get_annotations(self):
        """Devuelve una DataFrame con todas las anotaciones que recibe el constructor"""
        return self.anotaciones
    
    def add(self, anotacion:list|tuple):
        """Agrega una nueva anotación
            Args:
                anotacion : Nueva anotación a agregar (se espera la forma [inicio, duración, descripción])"""
        if len(anotacion) != 3:
            return False 
        elif self.anotaciones["Descripcion"].isin([anotacion[2]]).any(): # Si la descripcion del evento se repite en la columna, no se agrega la anotacion
            return False  
        else:
            self.anotaciones.loc[len(self.anotaciones)] = anotacion  # Agrega un fila
            return True 
    
    def remove(self):
        """Elimina una anotación específica
            Args:"""
        pass
    def find(self):
        """Busca y devuelve las anotaciones que coincidan con una descripción específica
            Args:"""
        pass
    def save(self):
        """Guarda las anotaciones en un archivo .csv
            Args:"""
        pass
    def load(self):
        """Carga las anotaciones desde un archivo .csv
            Args:"""
        pass

In [116]:
inicio = [5.0, 12.5, 20.0]
duracion = [2.0, 3.0, 3.5]
descripcion = ['Inicio_Experimento', 'Evento_1', 'Evento_2']

In [117]:
# Instanciar clase Anotaciones
anotaciones = Anotaciones(onset=inicio, duration=duracion, description=descripcion)

In [118]:
anotaciones.get_annotations()

   Inicio (s)  Duración (s)         Descripcion
0         5.0           2.0  Inicio_Experimento
1        12.5           3.0            Evento_1
2        20.0           3.5            Evento_2

In [126]:
nueva_anotacion = (6, 2, "Evento 3")
anotaciones.add(nueva_anotacion)
anotaciones.get_annotations()

   Inicio (s)  Duración (s)         Descripcion
0         5.0           2.0  Inicio_Experimento
1        12.5           3.0            Evento_1
2        20.0           3.5            Evento_2
3         6.0           2.0            Evento 3

In [ ]:
class RawSignal:
    """
    Clase para manejar señales fisiológicas en formato NumPy.
    Este constructor permite inicializar el objeto 'RawSignal' a partir de un array de datos ,
    con información adicional de los canales y el índice de la primera muestra.
    """
    
    def __init__(self, data, sfreq, info=None, anotaciones=None, first_samp=0):
        """
        Inicializa una instancia de la clase RawSignal.
        
        Parameters
        ----------
        data : np.ndarray
            Matriz de datos con forma '(n_canales , n_muestras)'.
        sfreq : float
            Frecuencia de muestreo de la señal en Hz.
        info: Objeto del tipo  info. Opcional. Por defecto es None.
            Información adicional sobre la señal. El diccionario contiene info relevante de la señal
        anotaciones : Anotaciones
            Objeto de tipo Anotaciones que almacena eventos asociados a la señal y al experimento.
        first_samp : int, optional
            Índice del primer muestreo a utilizar (default es 0).
        
        Raises
        ------
        ValueError
            Si el array 'data' no tiene la forma '(n_canales , n_muestras)'.
        ValueError
            Si el índice 'first_samp' está fuera del rango de la señal.
        """
        # Validar tipo de data
        if not isinstance(data, np.ndarray):
            raise ValueError("El parámetro 'data' debe ser un array de NumPy (np.ndarray).")

        if data.ndim != 2:
            raise ValueError("El array 'data' debe tener dos dimensiones: (n_canales, n_muestras).")

        n_muestras = data.shape[1]
        if not (0 <= first_samp < n_muestras):
            raise ValueError("El índice 'first_samp' está fuera del rango de muestras disponibles.")

        # Asignación de atributos
        self.data = data
        self.sfreq = sfreq
        self.info = info
        self.anotaciones = anotaciones
        self.first_samp = first_samp
        
    def get_data(self, picks=None, start=0, stop=0, reject=None, times=False):
        """
        Obtiene muestras de la señal en un rango dado.

        Parameters
        ----------
        picks : str o array_like, optional
            Canales o índices a extraer. Si es 'None', se seleccionan todos los canales.
        start : float, optional
            Tiempo inicial (en segundos) para extraer muestras (por defecto 0).
        stop : float, optional
            Tiempo final (en segundos) para extraer muestras (por defecto 0, que significa hasta el final de la señal).
        reject : float, optional
            Valor pico a pico de umbral para rechazar canales. Si una muestra supera este umbral, el canal se descarta (por defecto 'None').
        times : bool, optional
            Si es 'True', se retorna también el vector de tiempos asociado a las muestras.

        Returns
        -------
        np.ndarray
            Matriz con los datos seleccionados (n_canales x n_muestras).
        np.ndarray (opcional)
            Vector de tiempos (solo si 'times=True').

        Raises
        ------
        ValueError
            Si los índices seleccionados están fuera de rango.
        """
        
        n_canales, n_muestras = self.data.shape
    
        # Convertir start y stop de segundos a índices de muestra
        start_idx = int(start * self.sfreq)
        stop_idx = int(stop * self.sfreq) if stop > 0 else n_muestras

        if not (0 <= start_idx < stop_idx <= n_muestras):
            raise ValueError("Índices de tiempo fuera de rango.")

        # Seleccionar canales
        if picks is None:
            canales_idx = np.arange(n_canales)
        elif isinstance(picks, (list, np.ndarray)):
            canales_idx = np.array(picks)
        elif isinstance(picks, str):
            # Si info está disponible, buscar canal por nombre
            if self.info and "canales" in self.info:
                canales_idx = [i for i, ch in enumerate(self.info["canales"]) if ch == picks]
                if not canales_idx:
                    raise ValueError(f"Canal '{picks}' no encontrado.")
            else:
                raise ValueError("No se puede buscar por nombre sin metadatos de canales.")
        else:
            raise ValueError("Formato de 'picks' inválido. Debe ser None, str o lista de índices.")

        # Extraer datos seleccionados
        datos = self.data[np.array(canales_idx), start_idx:stop_idx]

        # Aplicar umbral de rechazo si se especifica
        if reject is not None:
            p2p = np.ptp(datos, axis=1)  # pico a pico por canal
            mask = p2p < reject
            datos = datos[mask]

        if times:
            tiempo_vector = np.arange(start_idx, stop_idx) / self.sfreq
            return datos, tiempo_vector

        return datos